version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=true

    depends_on:
      - db

  db:
    image: mongo:latest
    hostname: "agencia-mongo"
    environment:
      - "MONGO_INITDB_ROOT_DATABASE = agencia-turismo"
      - "MONGO_INITDB_ROOT_USERNAME = mongo"
      - "MONGO_INITDB_ROOT_PASSWORD = mongo"
    ports:
      - "27018:27017"


  frontend:
    build:
      context: ./frontend/my-material-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/my-material-app:/app
      - /app/node_modules

      
    depends_on:
      - web

volumes:
  postgres_data:
