version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - 50000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agencia_turismo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql

volumes:
  postgres_data:
